DROP TABLE IF EXISTS TB_HEROES;
CREATE TABLE TB_HEROES (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL 
)

--create
INSERT INTO TB_HEROES (NOME, PODER)
VALUES 
    ('Flash', 'Speed'),
    ('Batman', 'Money'),
    ('Green Lantern', 'power ring')

--read
SELECT * FROM TB_HEROES; 
SELECT * FROM TB_HEROES WHERE NOME = 'Flash';   

--update
UPDATE TB_HEROES
SET NOME='Superman', PODER='Force'
WHERE ID = 3;

--delete
DELETE FROM TB_HEROES WHERE ID = 2;